#pragma once

/**
 * #CEDF9F Primary
 * #A1D6B2 Secondary
 * #F5F0CD Background
 * #E8B86D Highlight
 * #81BFDA Accent
 * #333333 Text
 */

 // ILI9341 RGB565 colors converted from HEX

#define COLOR_PRIMARY    0xCE9D  // #CEDF9F
#define COLOR_SECONDARY  0xAD75  // #A1D6B2
#define COLOR_BACKGROUND 0xF79B  // #F5F0CD
#define COLOR_HIGHLIGHT  0xED91  // #E8B86D
#define COLOR_ACCENT     0x9EDD  // #81BFDA
#define COLOR_TEXT       0x4208  // #333333

#define SCROLLBAR_X 312
#define SCROLLBAR_W 8


#define COLOR_PRIMARY_32    COLOR_PRIMARY | (COLOR_PRIMARY << 16)
#define COLOR_SECONDARY_32  COLOR_SECONDARY | (COLOR_SECONDARY << 16)
#define COLOR_BACKGROUND_32  COLOR_BACKGROUND | (COLOR_BACKGROUND << 16)
#define COLOR_HIGHLIGHT_32  COLOR_HIGHLIGHT | (COLOR_HIGHLIGHT << 16)
#define COLOR_ACCENT_32     COLOR_ACCENT | (COLOR_ACCENT << 16)
#define COLOR_TEXT_32        COLOR_TEXT | (COLOR_TEXT << 16)